language: python
python:
  - "3.4"
env:
  - DJANGO=1.7.4
  - DJANGO=1.6.10
  - DJANGO=1.5.12
  - DJANGO=1.4.19
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt
branches:
  only:
    - master
script:
  - python manage.py test
matrix:
  fast_finish: true
notifications:
  email: false