language: python
python:
  - "3.4"
env:
  - TOERH_DJANGO_SECRET_KEY='@v9c-4ymi$o6xk@m24c5hy5)7vrme6_qk_pbd*7+p(!trld@o%'
  - DJANGO=1.7.4
  - DJANGO=1.6.10
  - DJANGO=1.5.12
  - DJANGO=1.4.19
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt
branches:
  only:
    - master
script:
  - python manage.py test
matrix:
  fast_finish: true
notifications:
  email: false
